language: node_js
node_js:
  - 12.14.1
branches:
  only:
    - master
cache:
  directories:
    - node_modules
before_install:
  - npm update
install:
  - npm install
script:
  - npm run build
deploy:
  provider: firebase
  token:
    secure: $FIREBASE_HOSTING_KEY